name: MLOps CI Workflow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # Menginstal library dari requirements.txt jika file tersebut ada
        if [ -f Membangun_Model/requirements.txt ]; then pip install -r Membangun_Model/requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # Menghentikan proses jika ada error sintaksis fatal
        flake8 Membangun_Model/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Menampilkan peringatan untuk format kode (tidak membatalkan workflow)
        flake8 Membangun_Model/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics